### ISSUE TITLE
Proposal: move dds tracepoints to RWM layers

### ISSUE THREAD

**Issue by cwecht** [ros2/ros2_tracing#73]
ros2profile needs a few tracepoints which are currently located in the DDS implementations itself, e.g. here in cyclonedds: https://github.com/christophebedard/cyclonedds/blob/instrumentation-lttng-update/src/core/ddsc/src/tracing_lttng.h

The tracepoints in question are:
- dds:create_writer
- dds:create_reader
- dds:write
- dds:read

AFAIK none of these tracepoints made it to the master branches of the respective DDS implementation. However for commercial products like RTI ConnextDDS it is probably almost impossible to introduce these tracepoints in their code base.
Additionally the current approach imposes a massive maintainance burden.

I had a look at rmw_cyclonedds and rmw_fastrtps and found that it should be possible to add the respective tracepoints there as well. I had added tracepoints to rmw_connextdds before, too:
- https://github.com/ros2/rmw_cyclonedds/commit/816c50682c9f7999de38205e9ee49c70f436e146
- https://github.com/ros2/rmw_fastrtps/commit/f2ac3e0ac05a6994b2daedfd4929a2b99924fd51
- https://github.com/ros2/rmw_connextdds/commit/3facbce260d712afab6000c17216b721b694abcc#diff-15424b0249cc41e5d4179bade17b540ec7d1edd8b20f7d60bc614fe7be0316d3

Please note that
1. these changes are not working right now because I didn't bother for the moment to migrate the tracepoint definitions to the respective repositories. These changes are only for showcaseing what's possible as a basis for discussion.
2. The changes in rmw_cyclonedds are a bit tricky as it is not easily possible to get a pointer to a writer/reader without setting a mutex on them. I just used to rmw-subscriber to fill the pointer field. This should suffice anyways.
3. The current implementation in rmw_connextdds introduces a quite massive performance penalty due DDS_DomainParticipant_get_current_time being really slow. It seems though, that it is possible to use other time souces here.

Based on these findings I propose to:
1. move dds:create_writer" and dds:create_reader to tracetools.
2. move "dds:write" and "dds:read" to tracetools as well or, at least the the source_timestamp field to ros2:rmw_publish, as ros2:rmw_publish and dds:write are usually realy close anyways.

Adding the source_timestamp to ros2:rmw_publish has the nice effect, that it would mirror ros2:rmw_take quite nicely then. In fact for ros2_profiling, if one only want's to analyse a system with lot's of nodes, the ros2:rmw_publish and ros2:rmw_take are needed for connexting different nodes; ros2:rcl_publish, ros2:rcl_take, ros2:rclcpp_publish and ros2:rclcpp_take (and dds:write and dds:read for that matter) would become optional in that case. In cases where the overhead of the tracing significantly impacts the system performance, this can be really valuable. 

Migrating ros2_tracing and ros2_profiling to other OSs like QNX would also be much simpler with these changes applied, as all required tracepoints would be defined in a single place.

I created this issue in order to ask for some feedback. Is anyone seeing any impediments or issues with the proposed changes?

**Comment by christophebedard** [comment]
Thanks for bringing this up! I agree that this has a lot of upsides.

The goals for the DDS instrumentation, in order of importance, are:

1. Collect the necessary information to be able to link published messages to received messages. This is of course the `source_timestamp` value. The DDS writer/reader fields are only used to link the `dds:write`/`dds:read` to their corresponding publisher/subscription.
   1. We do collect the DDS topic name, but it's not that useful
2. Have a tracepoint as close to the network/transport as possible so that we know exactly(-ish) when we've sent or received the message
   1. This (and symmetry) is the only reason I created `dds:read`, since it doesn't collect the `source_timestamp`
   2. The RMW and DDS tracepoints are very close together, so we don't strictly need anything in DDS

Therefore, if we can achieve that directly in RMW, then yeah it's even better. My only concerns are:

1. Are the proposed DDS API call changes acceptable? I assume so
3. Are there any potential side effects if we use, for example with Cyclone DDS, `std::chrono::system_clock::now().time_since_epoch().count()` instead of `dds_time()` for the `source_timestamp` on the publisher's side? It's not really a problem for tracing, since we only use them as IDs, but it could affect other users.

To add to your proposed changes, we could do a number of other optimizations:

1. (Merge `rmw_publish` with `dds:write` and `rmw_take` with `dds:create`, and remove the DDS writer/reader fields)
2. Remove `dds:create_writer` and `dds:create_reader`, since we don't need the DDS writer/reader fields
3. Remove `rmw_publisher_init` & `rmw_subscription_init`, since they're only used to link the ROS 2 pubs/subs to their DDS writer/reader through their GIDs

Regarding making a number of tracepoints effectively optional, if we remove the DDS writer, then we lose the link between `rmw_publish` and its publisher, since `rmw_publish` doesn't include the publisher (whereas `rmw_take` does include the subscription). However, we could always change `rmw_publish` to include the publisher. As you said, it would be valuable to reduce the number of required tracepoints.

Can you try to implement your proposed changes to make sure it works? No need for all the optimizations I mentioned above. Then you could open PRs and we could discuss with the `rmw_*` maintainers.
