### ISSUE TITLE
rcl_init miss

### ISSUE THREAD

**Issue by Autostone-c** [ros2/ros2_tracing#78]
![image](https://github.com/ros2/ros2_tracing/assets/50130211/23d9c945-d71b-4584-839e-9263f79c0ee7)
hi, i meet this error? i saw the other didnt show any about this

**Comment by christophebedard** [comment]
What version of ROS 2 are you using? What version of `tracetools_analysis`/`ros2trace_analysis` are you using?

**Comment by christophebedard** [comment]
Since there has been no response, I'm going to close this. Feel free to re-open the issue and provide the versions of ROS 2/`tracetools_analysis` that you're using if you're still facing this issue.

**Comment by nightduck** [comment]
I'm getting the exact same error. Using the default binaries that come with Ubuntu 24.04

tracetools-analysis: 3.0.0-5noble.20240426.184931

I follow steps 1 and 2 [here](https://docs.ros.org/en/rolling/Tutorials/Advanced/ROS2-Tracing-Trace-and-Analyze.html#step-1-trace). After killing my process and running
    
    ros2 run tracetools_analysis process ~/.ros/tracing/test

I get the same `missing events: {'Ros2Handler': {'ros2:rcl_init'}}` error that @Autostone-c received.

The catch: on the same machine, with the same versions, I receive no error when I run a standard application from a public repo. The issue is definitely my code (which is definitely invoking rcl_init), but I can't find out what is wrong.

@Autostone-c : 
![image](https://github.com/ros2/ros2_tracing/assets/10158631/c1594623-1f54-480d-a7b1-6d4a9d71b689)

**Comment by christophebedard** [comment]
> The catch: on the same machine, with the same versions, I receive no error when I run a standard application from a public repo. The issue is definitely my code (which is definitely invoking rcl_init), but I can't find out what is wrong.

Can you share the application you're tracing, or at least a minimal reproducer? Alternatively, you could use `gdb` to make sure that `rcl_init()` is called and that it runs the `TRACETOOLS_TRACEPOINT()` line. https://github.com/ros2/rcl/blob/6d53d24a863c3e9e4a41e9fe5f550271210d9d9d/rcl/src/rcl/init.c#L47

**Comment by christophebedard** [comment]
Or alternatively, you could just comment out this line, assuming that you don't need this data: https://github.com/ros-tracing/tracetools_analysis/blob/760dca9598a04a64b2e1aef0f8e419e8018c79d6/tracetools_analysis/tracetools_analysis/processor/ros2.py#L107. Then it won't complain about it.

**Comment by nightduck** [comment]
My application was directly linking to rcl code, specifically the rcl_timer_get_period function. When I moved this functionality down into a modified rclcpp layer, this issue disappeared.

So my guess is it's a linking issue. When you link directly to rcl, the tracer gets uppity.

**Comment by nightduck** [comment]
Belay that. The issue came back. It does not seem to have anything to do with rcl_init in particular, because if I just execute the following simple script:

    from tracetools_analysis.loading import load_file
    from tracetools_analysis.processor import Processor
    from tracetools_analysis.processor.cpu_time import CpuTimeHandler
    from tracetools_analysis.processor.ros2 import Ros2Handler
    from tracetools_analysis.utils.cpu_time import CpuTimeDataModelUtil
    from tracetools_analysis.utils.ros2 import Ros2DataModelUtil
    
    # Load trace directory or converted trace file
    events = load_file('~/.ros/tracing/my_trace')
    
    print(events)

I get this printout:

    found converted file: /home/ubuntu/.ros/tracing/my_trace/converted
    []

**Comment by nightduck** [comment]
For those who find this issue in the future, it can be caused by the following problems:

- The aforementioned rcl linking issue. Details unclear, but refrain from linking directly to rcl
- Mismatched root permissions between the tracer and the program. If the program is launched with root, the tracer must be launched with root
- Python environments. If your program's terminal has sourced a python environment that your tracer hasn't sourced, it will not work, (even if you prepend `env PATH="$PATH" LD_LIBRARY_PATH="$LD_LIBRARY_PATH"` to your command)
- Failing to prepend the `sudo env PATH="$PATH" LD_LIBRARY_PATH="$LD_LIBRARY_PATH"`. If you open a root terminal with `sudo su`, source ros and execute from there: also will not work.

The method I got working to execute a program in root is to put the following in a bash program:

    ros2 trace start test-trace
    ./path/to/my/program
    ros2 trace stop test-trace

And then execute that script with:

    sudo env PATH="$PATH" LD_LIBRARY_PATH="$LD_LIBRARY_PATH" bash run_and_trace_my_program.sh

**Comment by christophebedard** [comment]
Just curious: why do you need to run as root?

**Comment by nightduck** [comment]
> Just curious: why do you need to run as root?

My application uses real-time priorities
